Update testing plots, revert model changes
Got AttributeError: AquaCropModel object has no attribute '_outputs'...reverting last change to see if it fixes.